# Rule definitions - all 95+ SDC rules
# Auto-split from app.R - do not edit the monolithic file

RULES <- list(
  TAB001 = list(id="TAB-001", label="Participant / Sample Identifiers",
    outcome="RED",
    check="Detects column headers matching known participant identifier names: participant_id, imaging_id, sample_id, subject_id and equivalent patterns", file_types=c("tabular","script")),
  TAB002 = list(id="TAB-002", label="PII Patterns in Cell Values",
    outcome="RED",
    check="Scans string cell content for NHS number patterns, email addresses, and DOB formats", file_types=c("tabular")),
  TAB003 = list(id="TAB-003", label="Individual-Level (Per-Participant) Identifier",
    outcome="AMBER",
    check="Flags a high-cardinality column (uniqueness > 0.85, row count > 10) that may be a per-participant identifier. Synthetic IDs (sequential, UUID, hash) are noted as not externally-linkable; unrecognised IDs are flagged for reviewer confirmation. Real-world identifiers (NHS/CHI) are caught with higher confidence by TAB-001 and TAB-018.", file_types=c("tabular")),
  TAB004 = list(id="TAB-004", label="Sensitive Phenotype Columns",
    outcome="RED",
    check="Column headers matched against sensitive phenotype list: hiv, mental_health, substance_use, sexual_orientation, self_harm, suicide, domestic_abuse", file_types=c("tabular","script")),
  TAB005 = list(id="TAB-005", label="Unmasked Small Counts (< 5)",
    outcome="RED",
    check="Integer values 1-4 found in columns explicitly named as count/frequency fields (e.g. n, n_cases, total, patient_count, freq). Anchored patterns only - does not fire on occurrence, exposure, or other compound column names.", file_types=c("tabular")),
  TAB006 = list(id="TAB-006", label="Raw Source Field Names",
    outcome="RED",
    check="Column headers matching raw source field code pattern f.XXXXX.X.X indicating an unmodified data extract", file_types=c("tabular")),
  TAB007 = list(id="TAB-007", label="Restricted Field in Summary Data",
    outcome="AMBER",
    check="Summary tables referencing known restricted field names: systolic_bp, brain_*, mri_*, dxa_*, ocular_*", file_types=c("tabular")),
  TAB008 = list(id="TAB-008", label="File Size > 5 GB",
    outcome="AMBER",
    check="File size exceeds 5,000 MB threshold", file_types=c("tabular","script","genomic","archive")),
  TAB009 = list(id="TAB-009", label="Percentage Back-Calculation Risk",
    outcome="RED",
    check="A percentage or proportion column combined with a known denominator (N, total) implies a count below the suppression threshold. The suppressed count is recoverable by multiplication.",
    file_types=c("tabular")),
  TAB010 = list(id="TAB-010", label="Rare Category Exposure",
    outcome="RED",
    check="A categorical column contains one or more values appearing fewer times than the suppression threshold. Rare categories act as quasi-identifiers even without an explicit ID column.",
    file_types=c("tabular")),
  TAB011 = list(id="TAB-011", label="Over-Precise Continuous Variable",
    outcome="AMBER",
    check="A date column uses day-level precision (YYYY-MM-DD), a postcode column contains full sector-level codes, or an age column contains sub-year decimal values. Each significantly increases re-identification risk.",
    file_types=c("tabular")),
  TAB012 = list(id="TAB-012", label="Free Text / Narrative Columns",
    outcome="AMBER",
    check="Column names matching free-text patterns (notes, comments, narrative, description, history, reason, remarks etc.) detected. Free text fields frequently contain names, dates, locations, and contextual details that can identify individuals even when structured columns appear clean.",
    file_types=c("tabular")),
  TAB013 = list(id="TAB-013", label="Secondary Suppression Risk",
    outcome="RED",
    check="In a summary table, suppressed cells (values marked as <5 or below the count threshold) appear alongside row or column totals. The suppressed count is recoverable by subtraction from the total, defeating the purpose of suppression.",
    file_types=c("tabular")),
  TAB014 = list(id="TAB-014", label="Derived Temporal / Spatial Identifiers",
    outcome="AMBER",
    check="Column names suggest derived temporal or spatial variables (time_since_, age_at_, days_in_, distance_from_, duration_, interval_) which remain quasi-identifying despite being computed from raw identifiers. These are particularly re-identifying when combined with diagnosis or site information.",
    file_types=c("tabular")),
  TAB015 = list(id="TAB-015", label="K-Anonymity Risk",
    outcome="RED",
    check=paste0(
      "Computes k-anonymity across recognised quasi-identifier columns (age, sex, ethnicity, ",
      "geography, diagnosis date, occupation, derived temporal variables). k is the minimum ",
      "number of individuals sharing each unique combination of quasi-identifier values. ",
      "k below the suppression threshold means at least one individual can be distinguished ",
      "from all others by their combination of values alone. NHS SDC guidance recommends k \u2265 5."),
    file_types=c("tabular")),
  TAB016 = list(id="TAB-016", label="K-Anonymity \u2014 Cannot Estimate",
    outcome="AMBER",
    check=paste0(
      "K-anonymity could not be computed automatically. Either no quasi-identifier columns were ",
      "recognised from the column names, or the file exceeds the configured row limit for ",
      "automated computation. Manual k-anonymity assessment is required if this file contains ",
      "individual-level data."),
    file_types=c("tabular")),
  TAB017 = list(id="TAB-017", label="Statistical File \u2014 Sensitive Value/Variable Labels",
    outcome="RED",
    check=paste0(
      "Stata/SAS/SPSS files embed variable labels (full English descriptions of each column) and value labels ",
      "(text mapping for coded numeric values). These labels can expose sensitive phenotype categories ",
      "even when the column values themselves are numeric codes. Rule checks attr(col,'label') and ",
      "names(attr(col,'labels')) against the configured sensitive phenotype vocabulary."),
    file_types=c("statistical")),
  TAB018 = list(id="TAB-018", label="PII Value Scan \u2014 Identifiers in Cell Values",
    outcome="RED",
    check=paste0(
      "Scans cell values in string columns (sample of first 500 rows) for NHS numbers ",
      "(with check-digit validation), National Insurance numbers, CHI numbers (Scotland), ",
      "and email addresses. Fires per pattern type found, per column."),
    file_types=c("tabular","statistical")),
  TAB019 = list(id="TAB-019", label="PII Value Scan \u2014 UK Postcode in Cell Values",
    outcome="RED",
    check="Detects full UK postcodes in string column cell values. Full postcodes identify approximately 15 households and are classified as PII. Partial outward codes (e.g. SW1) are flagged AMBER.",
    file_types=c("tabular","statistical")),
  TAB020 = list(id="TAB-020", label="PII Value Scan \u2014 UK Phone Number in Cell Values",
    outcome="AMBER",
    check="Detects UK phone number patterns (mobile 07xxx, landline 01/02/03xxx, international +44) in string column cell values.",
    file_types=c("tabular","statistical")),
  TAB021 = list(id="TAB-021", label="PII Value Scan \u2014 Date of Birth Pattern in Free-Text",
    outcome="RED",
    check="Detects date-of-birth patterns (DD/MM/YYYY, YYYY-MM-DD, day-month-year prose) in string columns not already identified as date columns by name heuristic.",
    file_types=c("tabular","statistical")),
  TAB022 = list(id="TAB-022", label="Column Uniqueness Profile",
    outcome="GREEN",
    check="Informational: per-column summary showing cardinality, uniqueness percentage, missing value rate, and numeric range. Always fires to give the reviewer a statistical overview of the dataset structure.",
    file_types=c("tabular","statistical")),
  TAB023 = list(id="TAB-023", label="Suppression Consistency \u2014 Back-Calculation Risk",
    outcome="RED",
    check=paste0(
      "Aggregated table contains suppression markers (<5, *, [c], -) in numeric cells. ",
      "Checks whether any suppressed cell can be uniquely determined by subtracting ",
      "non-suppressed values from a row or column total. If so, the suppression is ineffective."),
    file_types=c("tabular","statistical")),
  TAB024 = list(id="TAB-024", label="Free-Text \u2014 Named Entity and Quasi-Identifier Pattern",
    outcome="RED",
    check=paste0(
      "Free-text string columns scanned for: person name patterns (title + capitalized words), ",
      "UK place names (county/city), NHS institution names, and quasi-identifier composite ",
      "signatures (age + sex + occupation + geography in a single cell). Fires per pattern type."),
    file_types=c("tabular","statistical")),
  TAB025 = list(id="TAB-025", label="Pre-Aggregated Pivot / Cross-Tabulation Table",
    outcome="GREEN",
    check=paste0(
      "File recognised as a pandas multi-index pivot or cross-tabulation table ",
      "(blank index-name cell and a second header level). These are pre-aggregated ",
      "summary tables, not flat per-row microdata, so row-level disclosure rules ",
      "(identifier columns, k-anonymity, cardinality, PII scans) do not apply. ",
      "Where the file is part of an ACRO submission, the ACRO statistical disclosure ",
      "control result is the authoritative check."),
    file_types=c("tabular")),
  STAT001 = list(id="STAT-001", label="Statistical File \u2014 Individual-Level or Sensitive Data",
    outcome="RED",
    check="Stata (.dta), SAS (.sas7bdat), or SPSS (.sav) file. All standard tabular disclosure rules (TAB-001 through TAB-016) applied after reading via haven.",
    file_types=c("statistical")),
  STAT002 = list(id="STAT-002", label="Statistical File \u2014 haven Not Available",
    outcome="AMBER",
    check="haven R package is not installed. Statistical file content cannot be inspected automatically.",
    file_types=c("statistical")),
  ARC003 = list(id="ARC-003", label="Archive Contains High-Risk File Types",
    outcome="RED",
    check=paste0(
      "Archive manifest lists files with extensions associated with high disclosure risk that cannot be ",
      "inspected through the archive wrapper: statistical formats (.dta/.sas7bdat/.sav), databases (.db/.sqlite), ",
      "serialised objects (.rds/.RData), genomic files (.vcf/.bam), NIfTI images (.nii/.nii.gz). ",
      "Each must be extracted and assessed individually."),
    file_types=c("archive")),
  ARC004 = list(id="ARC-004", label="Archive Contains Tabular or Script Files",
    outcome="AMBER",
    check="Archive manifest lists tabular (.csv/.xlsx) or script (.R/.py/.sql/.ipynb) files that require individual inspection. Extract and submit each file separately for full disclosure assessment.",
    file_types=c("archive")),
  ARC005 = list(id="ARC-005", label="Archive Contains Many Files",
    outcome="AMBER",
    check="Archive contains more than the configured file count threshold. Large archives may obscure content volume. Review the manifest carefully before approving egress.",
    file_types=c("archive")),
  NII001 = list(id="NII-001", label="NIfTI \u2014 Identifiers in Header Metadata",
    outcome="RED",
    check="NIfTI header fields (descrip, aux_file, intent_name) contain patterns matching NHS numbers, date-of-birth formats, or participant identifier patterns.",
    file_types=c("nifti")),
  NII002 = list(id="NII-002", label="NIfTI \u2014 Head/Brain Imaging (Facial Reconstruction Risk)",
    outcome="AMBER",
    check=paste0(
      "File name or NIfTI header metadata indicates head or brain imaging (MRI/fMRI/T1/T2/BOLD/anatomical). ",
      "3D head volumes can be surface-rendered to reconstruct a recognisable facial likeness. ",
      "Pixel-level de-facing cannot be confirmed from the header alone."),
    file_types=c("nifti")),
  NII003 = list(id="NII-003", label="NIfTI \u2014 3D Volumetric Image",
    outcome="AMBER",
    check="3D NIfTI volume detected without specific head/brain indicators in filename or header. Imaging data carries inherent re-identification risk from anatomical structure. Manual review required.",
    file_types=c("nifti")),
  NII004 = list(id="NII-004", label="NIfTI \u2014 Header Parse Failure",
    outcome="AMBER",
    check="NIfTI header could not be read. File may be corrupt, use NIfTI-2 format with unsupported encoding, or be a paired .img file without its companion .hdr.",
    file_types=c("nifti")),
  NII005 = list(id="NII-005", label="NIfTI \u2014 Header Checked: No Identifiers",
    outcome="GREEN",
    check="NIfTI header parsed successfully. Metadata fields (descrip, aux_file, intent_name) contain no identifier patterns. Note: this covers header metadata only; pixel content and anatomical reconstruction risk require manual review.",
    file_types=c("nifti")),
  SCR001 = list(id="SCR-001", label="Embedded Participant Identifiers in Script",
    outcome="RED",
    check="Script source scanned for participant identifier patterns, ID vectors, or identifier column references", file_types=c("script")),
  SCR002 = list(id="SCR-002", label="Inline Data Block in Notebook/Script",
    outcome="AMBER",
    check="Detects data.frame(), tibble(), or pd.DataFrame() constructs with inline row data", file_types=c("script")),
  SCR003 = list(id="SCR-003", label="Sensitive Phenotype References in Script",
    outcome="RED",
    check="Script scanned for sensitive phenotype terms used in active coding contexts only: quoted strings, dplyr filter/select/mutate arguments, variable assignments, or dataframe column references. Comment lines and bare mentions in unrelated identifiers (e.g. drug_exposure, depression_era) are excluded.", file_types=c("script")),
  GEN001 = list(id="GEN-001", label="VCF Per-Sample Genotype Columns",
    outcome="RED",
    check="VCF files with FORMAT/SAMPLE columns where GT field is present with one or more individual sample columns", file_types=c("genomic")),
  GEN002 = list(id="GEN-002", label="Sensitive Phenotype in Genomic File",
    outcome="RED",
    check="VCF metadata or annotation fields reference sensitive phenotype categories", file_types=c("genomic")),
  GEN003 = list(id="GEN-003", label="GWAS Summary Statistics - Standard Format",
    outcome="GREEN",
    check="File contains standard GWAS summary stat columns (SNP/CHR/BP/BETA/SE/P) with no per-sample data", file_types=c("genomic","tabular")),
  GEN004 = list(id="GEN-004", label="VCF - Rare Variant (MAF < 1%)",
    outcome="RED",
    check=paste0("One or more variants in the VCF INFO field have AF= or MAF= annotation below 0.01 (1%). ",
      "Rare variants in small cohorts can identify individuals through a unique variant profile. ",
      "MAF filters should be applied before egress."),
    file_types=c("genomic")),
  GEN005 = list(id="GEN-005", label="VCF - Sample Size Embedded in INFO",
    outcome="AMBER",
    check=paste0("INFO field contains NS= (number of samples) or AN= (allele number, implying N=AN/2) annotations. ",
      "The implied sample size should be verified against the approved cohort size."),
    file_types=c("genomic")),
  GEN006 = list(id="GEN-006", label="VCF - Pedigree or Individual Sample Metadata",
    outcome="RED",
    check=paste0("VCF meta-information lines contain ##PEDIGREE= or ##SAMPLE= records. ",
      "These encode family relationships and/or individual identifiers and are highly disclosive. ",
      "They must be stripped before egress."),
    file_types=c("genomic")),
  GEN007 = list(id="GEN-007", label="VCF - Per-Sample Depth and Quality Fields",
    outcome="AMBER",
    check=paste0("FORMAT field contains DP (read depth) and/or GQ (genotype quality) per-sample annotations. ",
      "These parameters reveal sequencing platform characteristics and may narrow the originating lab when combined with other metadata."),
    file_types=c("genomic")),
  GEN008 = list(id="GEN-008", label="PLINK FAM - Individual-Level Phenotype and Pedigree",
    outcome="RED",
    check=paste0("PLINK .fam file contains one row per individual with family ID, individual ID, ",
      "paternal/maternal IDs (pedigree structure), biological sex, and phenotype status. ",
      "This file almost always constitutes disclosable individual-level data."),
    file_types=c("genomic")),
  GEN009 = list(id="GEN-009", label="PLINK BIM - Variant Map",
    outcome="AMBER",
    check=paste0("PLINK .bim variant map file. Not directly identifying but reveals the exact variant panel used, ",
      "which may be considered sensitive under some data access agreements. ",
      "Reviewed for rare-disease-associated rsID prefixes."),
    file_types=c("genomic")),
  GEN010 = list(id="GEN-010", label="PLINK BED - Binary Genotype Matrix",
    outcome="RED",
    check=paste0("PLINK .bed binary genotype file detected via magic bytes (0x6c 0x1b 0x01). ",
      "Contains individual-level genotype data for all variants in the .bim file. ",
      "Cannot be egressed without specialist review and explicit approval."),
    file_types=c("genomic")),
  GEN011 = list(id="GEN-011", label="PGEN - PLINK2 Binary Genotype File",
    outcome="RED",
    check=paste0("PLINK2 .pgen binary genotype file detected via magic bytes (0x6c 0x1b). ",
      "Contains individual-level genotype data. Cannot be egressed without specialist review."),
    file_types=c("genomic")),
  GEN012 = list(id="GEN-012", label="PSAM - PLINK2 Individual Phenotype/Covariate File",
    outcome="RED",
    check=paste0("PLINK2 .psam file: individual-level sample metadata with phenotypes and covariates. ",
      "Equivalent to PLINK1 .fam but may contain additional covariate columns. Always disclosable."),
    file_types=c("genomic")),
  GEN013 = list(id="GEN-013", label="GWAS Summary - Small Sample Size (N < 100)",
    outcome="AMBER",
    check=paste0("A sample size column (N, NEFF, NCAS, NCON, N_cases) in a GWAS summary statistics file ",
      "has a maximum value below 100. Summary statistics from very small cohorts may allow ",
      "individual-level reconstruction from association signals."),
    file_types=c("genomic","tabular")),
  GEN014 = list(id="GEN-014", label="GWAS Summary - Unexpectedly Low Variant Count",
    outcome="AMBER",
    check=paste0("File claims to be GWAS summary statistics (GEN-003 fired) but contains fewer than 1,000 rows. ",
      "A genuine genome-wide analysis typically covers hundreds of thousands of variants. ",
      "A small row count may indicate a filtered subset derived from individual-level results."),
    file_types=c("genomic","tabular")),
  GEN015 = list(id="GEN-015", label="GWAS Summary - Extreme Association Signal",
    outcome="AMBER",
    check=paste0("A p-value column contains values below 5×10⁻³⁰ in a file with fewer than 500 samples. ",
      "Extreme signals in small cohorts can point to individual contributors."),
    file_types=c("genomic","tabular")),
  ARC001 = list(id="ARC-001", label="Encrypted or Proprietary Archive",
    outcome="RED",
    check="Archive filename or binary markers indicate encryption, password protection, or proprietary format", file_types=c("archive")),
  ARC002 = list(id="ARC-002", label="Standard Archive - Contents Not Yet Inspected",
    outcome="AMBER",
    check="Standard ZIP/TAR archive that can be unpacked; contents require recursive Airlock Checker inspection before a final decision", file_types=c("archive")),
  BIN001 = list(id="BIN-001", label="Binary File (No Recognised Format)",
    outcome="RED",
    check="File extension and magic bytes do not match any permitted egress format", file_types=c("binary")),
  IMG001 = list(id="IMG-001", label="Interactive Plot Detected",
    outcome="RED",
    check="SVG file contains JavaScript, onclick handlers, or Plotly/D3 interactive plot markers", file_types=c("image")),
  IMG002 = list(id="IMG-002", label="Participant Annotation in Plot",
    outcome="RED",
    check="SVG text layer contains 7-digit numeric patterns consistent with participant identifier values, or the word 'patient' (case-insensitive)", file_types=c("image")),
  IMG003 = list(id="IMG-003", label="Raster Image \u2014 Pixel Content Cannot Be Inspected",
    outcome="AMBER",
    check=paste0(
      "PNG, JPEG, BMP, and TIFF files store content as pixel data. Without OCR, any text, ",
      "patient annotations, or demographic information burned into the image are invisible to ",
      "automated inspection. The filename has been checked but pixel content requires manual ",
      "visual review. SVG files are fully inspected as structured XML and can earn GREEN."),
    file_types=c("image")),
  IMG004 = list(id="IMG-004", label="Circos / IGV / Oncoplot / Genetic Visualisation",
    outcome="AMBER",
    check="Filename or content suggests circos, IGV screenshot, oncoplot, mutational signature, or tumour mutational burden", file_types=c("image")),
  PDF001 = list(id="PDF-001", label="Encrypted or Password-Protected PDF",
    outcome="RED",
    check="PDF binary header or content indicates encryption or password protection", file_types=c("document")),
  PDF002 = list(id="PDF-002", label="Participant Identifier in PDF Text",
    outcome="RED",
    check="Extracted PDF text contains participant identifier patterns, NHS numbers, DOB formats, or column names matching known identifier fields", file_types=c("document")),
  PDF003 = list(id="PDF-003", label="Sensitive Phenotype in PDF Text",
    outcome="RED",
    check="Extracted PDF text references sensitive phenotype categories (HIV, mental health, substance use, sexual orientation etc.)", file_types=c("document")),
  PDF004 = list(id="PDF-004", label="Unmasked Small Counts in PDF",
    outcome="RED",
    check="PDF text contains count/frequency values of 1-4 adjacent to count-indicating words (n=, N=, count, cases, n_cases, total)", file_types=c("document")),
  PDF005 = list(id="PDF-005", label="Restricted Field References in PDF",
    outcome="AMBER",
    check="PDF text references known restricted data fields: brain MRI, DXA, abdominal MRI, OCT, restricted imaging phenotypes", file_types=c("document")),
  PDF006 = list(id="PDF-006", label="PDF Text Extraction Failed",
    outcome="AMBER",
    check="PDF text extraction returned no content. The file may be image-only (scanned), encrypted, or corrupted. Manual review required.", file_types=c("document")),
  PDF007 = list(id="PDF-007", label="Standard Research Document",
    outcome="GREEN",
    check="PDF text extracted and checked successfully. No participant identifiers, sensitive phenotypes, small unmasked counts, or restricted fields detected.", file_types=c("document")),

  # ── Wave 1: File type blind spots ────────────────────────────────────────
  SCR006 = list(id="SCR-006", label="Rendered Output in Notebook",
    outcome="AMBER",
    check="Jupyter (.ipynb) notebook contains non-empty cell outputs. Code inspection alone does not cover embedded execution results - data tables, printed data frames, or values may be present.",
    file_types=c("script")),
  SER001 = list(id="SER-001", label="Serialised R Object",
    outcome="AMBER",
    check="File is a serialised R object (.rds / .RData). Content cannot be assessed without deserialisation. Manual review required before egress.",
    file_types=c("serialised")),
  SER002 = list(id="SER-002", label="Large Serialised R Object",
    outcome="RED",
    check="Serialised R object exceeds the configured size threshold, indicating it likely contains a substantial data structure rather than a compact model summary.",
    file_types=c("serialised")),
  DAT001 = list(id="DAT-001", label="SQLite Database File",
    outcome="RED",
    check="File is a SQLite database (confirmed by magic bytes). Databases can contain multiple tables of participant-level data and cannot be automatically assessed without opening the file.",
    file_types=c("database")),
  COL001 = list(id="COL-001", label="Columnar Data Format (Parquet / Feather)",
    outcome="AMBER",
    check="File is a columnar data format (Parquet or Feather/Arrow IPC). These formats commonly hold large research datasets. Content cannot be assessed without the arrow package - manual review required.",
    file_types=c("columnar")),

  # ── DICOM medical images ──────────────────────────────────────────────────
  DCM001 = list(id="DCM-001", label="DICOM - Direct Patient Identifiers in Tags",
    outcome="RED",
    check=paste0(
      "DICOM metadata tags contain non-empty values in direct identifier fields: ",
      "PatientName (0010,0010), PatientID (0010,0020), PatientBirthDate (0010,0030), ",
      "ReferringPhysicianName (0008,0090), or AccessionNumber (0008,0050). ",
      "These tags must be empty or contain only anonymised values before egress."),
    file_types=c("dicom")),
  DCM002 = list(id="DCM-002", label="DICOM - Burned-In Patient Annotation",
    outcome="RED",
    check=paste0(
      "The DICOM tag BurnedInAnnotation (0028,0301) is set to YES, indicating that ",
      "patient demographic information has been rendered directly into the pixel data. ",
      "This cannot be removed by tag stripping - the image pixels themselves must be ",
      "de-annotated before egress."),
    file_types=c("dicom")),
  DCM003 = list(id="DCM-003", label="DICOM - Head Imaging: Facial Reconstruction Risk",
    outcome="AMBER",
    check=paste0(
      "Modality is MR or CT and body part or series description indicates head, brain, ",
      "skull, face, or cranial imaging. 3D head MRI and CT volumes can be used to ",
      "reconstruct a recognisable facial surface, constituting a biometric re-identification ",
      "risk even after tag anonymisation. Manual specialist review required."),
    file_types=c("dicom")),
  DCM004 = list(id="DCM-004", label="DICOM - Study Date at Day Precision",
    outcome="AMBER",
    check=paste0(
      "StudyDate (0008,0020) or ContentDate (0008,0023) contains a full date at day-level ",
      "precision. Combined with modality and institution, a precise study date significantly ",
      "increases re-identification risk. Dates should be shifted or truncated to year only ",
      "before egress."),
    file_types=c("dicom")),
  DCM005 = list(id="DCM-005", label="DICOM - Institution or Equipment Identifiers",
    outcome="AMBER",
    check=paste0(
      "Tags InstitutionName (0008,0080), InstitutionAddress (0008,0081), or StationName ",
      "(0008,1010) contain non-empty values. These identify the scanning site and equipment, ",
      "which may narrow re-identification to patients treated at a specific centre. ",
      "Review whether these tags need to be retained for scientific purposes."),
    file_types=c("dicom")),
  DCM006 = list(id="DCM-006", label="DICOM - File Could Not Be Parsed",
    outcome="AMBER",
    check=paste0(
      "The DICOM file could not be read by oro.dicom. The file may be corrupted, ",
      "use a proprietary transfer syntax not supported by the parser, or be a DICOMDIR ",
      "index file. Manual review of the file and its contents is required before egress."),
    file_types=c("dicom")),
  DCM007 = list(id="DCM-007", label="DICOM - Tags Checked: No Direct Identifiers",
    outcome="GREEN",
    check=paste0(
      "DICOM tags parsed successfully. Direct identifier tags (PatientName, PatientID, ",
      "PatientBirthDate, ReferringPhysician, AccessionNumber) are empty or absent. ",
      "BurnedInAnnotation is NO or absent. Note: this check covers metadata only. ",
      "Head imaging files require separate manual review for pixel-level reconstruction risk."),
    file_types=c("dicom")),

  # ── Office documents (.docx / .odt) ──────────────────────────────────────────
  DOC001 = list(id="DOC-001", label="Encrypted or Password-Protected Document",
    outcome="RED",
    check="Word/ODF document cannot be opened as a ZIP archive - likely encrypted or password-protected.",
    file_types=c("office")),
  DOC002 = list(id="DOC-002", label="Participant Identifier in Document",
    outcome="RED",
    check="Extracted document text contains participant identifier patterns, NHS numbers, DOB formats, or known identifier field names.",
    file_types=c("office")),
  DOC003 = list(id="DOC-003", label="Sensitive Phenotype in Document",
    outcome="RED",
    check="Extracted document text references sensitive phenotype categories (HIV, mental health, substance use, sexual orientation etc.).",
    file_types=c("office")),
  DOC004 = list(id="DOC-004", label="Unmasked Small Counts in Document",
    outcome="RED",
    check="Document text contains count values below the configured threshold adjacent to count-indicating terms (n=, N=, cases, total).",
    file_types=c("office")),
  DOC005 = list(id="DOC-005", label="Restricted Field References in Document",
    outcome="AMBER",
    check="Document text references known restricted data fields: brain MRI, DXA, abdominal MRI, OCT, restricted imaging phenotypes.",
    file_types=c("office")),
  DOC006 = list(id="DOC-006", label="Text Extraction Failed",
    outcome="AMBER",
    check="Document text could not be extracted. File may be legacy .doc format or corrupted. Manual review required.",
    file_types=c("office")),
  DOC007 = list(id="DOC-007", label="Standard Document",
    outcome="GREEN",
    check="Document text extracted and checked. No participant identifiers, sensitive phenotypes, unmasked counts, or restricted fields detected.",
    file_types=c("office")),

  # ── HTML / web pages ─────────────────────────────────────────────────
  HTM001 = list(id="HTM-001", label="Interactive / Executable JavaScript in HTML",
    outcome="RED",
    check="HTML file contains <script> blocks or interactive library markers (Plotly, D3, Highcharts, Shiny, observable). Interactive outputs may embed raw participant-level data.",
    file_types=c("webpage")),
  HTM002 = list(id="HTM-002", label="Participant Identifier in HTML",
    outcome="RED",
    check="HTML text content contains participant identifier patterns, NHS numbers, DOB formats, or known identifier field names.",
    file_types=c("webpage")),
  HTM003 = list(id="HTM-003", label="Sensitive Phenotype in HTML",
    outcome="RED",
    check="HTML text content references sensitive phenotype categories (HIV, mental health, substance use, sexual orientation etc.).",
    file_types=c("webpage")),
  HTM004 = list(id="HTM-004", label="Unmasked Small Counts in HTML",
    outcome="RED",
    check="HTML text contains count values below the configured threshold adjacent to count-indicating terms.",
    file_types=c("webpage")),
  HTM005 = list(id="HTM-005", label="Restricted Field References in HTML",
    outcome="AMBER",
    check="HTML text references known restricted data fields: brain MRI, DXA, abdominal MRI, OCT, restricted imaging phenotypes.",
    file_types=c("webpage")),
  HTM006 = list(id="HTM-006", label="Large Inline Data Table",
    outcome="AMBER",
    check="HTML contains a table with more than the configured row threshold - potentially individual-level tabular data embedded in a rendered notebook or report.",
    file_types=c("webpage")),
  HTM007 = list(id="HTM-007", label="Standard HTML Output",
    outcome="GREEN",
    check="HTML checked for scripts, participant identifiers, sensitive phenotypes, counts, restricted fields, and large tables. None detected.",
    file_types=c("webpage")),

  # ── JSON ──────────────────────────────────────────────────────────────────
  JSON001 = list(id="JSON-001", label="Credentials or Secrets in JSON",
    outcome="RED",
    check="JSON keys matching credential patterns: api_key, password, access_token, secret, private_key, auth_token, client_secret. Should never be egressed.",
    file_types=c("json")),
  JSON002 = list(id="JSON-002", label="Participant Identifier in JSON",
    outcome="RED",
    check="JSON text contains participant identifier patterns, NHS numbers, DOB formats, or known identifier field names as keys or values.",
    file_types=c("json")),
  JSON003 = list(id="JSON-003", label="Sensitive Phenotype in JSON",
    outcome="RED",
    check="JSON text references sensitive phenotype categories in field names or string values.",
    file_types=c("json")),
  JSON004 = list(id="JSON-004", label="Large Record Array in JSON",
    outcome="AMBER",
    check="JSON contains an array with many objects (estimated from closing-brace count), suggesting individual-level records rather than a summary.",
    file_types=c("json")),
  JSON005 = list(id="JSON-005", label="Standard JSON",
    outcome="GREEN",
    check="JSON checked for credentials, participant identifiers, sensitive phenotypes, and large record arrays. None detected.",
    file_types=c("json")),

  # ── XML ───────────────────────────────────────────────────────────────────
  XML001 = list(id="XML-001", label="Health Data Standard Detected",
    outcome="RED",
    check="XML contains FHIR, HL7, or CDA markers - these standards represent individual patient records and should never be egressed without explicit clinical governance approval.",
    file_types=c("xml")),
  XML002 = list(id="XML-002", label="Participant Identifier in XML",
    outcome="RED",
    check="XML element content or attribute values contain participant identifier patterns, NHS numbers, or DOB formats.",
    file_types=c("xml")),
  XML003 = list(id="XML-003", label="Sensitive Phenotype in XML",
    outcome="RED",
    check="XML text content references sensitive phenotype categories.",
    file_types=c("xml")),
  XML004 = list(id="XML-004", label="Large Repeating Record Structure",
    outcome="AMBER",
    check="XML contains many repetitions of the same element tag, suggesting a record-per-row data structure rather than a configuration or summary document.",
    file_types=c("xml")),
  XML005 = list(id="XML-005", label="Standard XML",
    outcome="GREEN",
    check="XML checked for health data standards, participant identifiers, sensitive phenotypes, and large record structures. None detected.",
    file_types=c("xml")),

  # ── Markdown ──────────────────────────────────────────────────────────────
  MD001 = list(id="MD-001", label="Participant Identifier in Markdown",
    outcome="RED",
    check="Markdown prose or table content contains participant identifier patterns, NHS numbers, or DOB formats.",
    file_types=c("markdown")),
  MD002 = list(id="MD-002", label="Sensitive Phenotype in Markdown",
    outcome="RED",
    check="Markdown text references sensitive phenotype categories outside of code blocks.",
    file_types=c("markdown")),
  MD003 = list(id="MD-003", label="Large Embedded Data Table",
    outcome="AMBER",
    check="Markdown contains a pipe table with more than the configured row threshold, suggesting individual-level data embedded in a report.",
    file_types=c("markdown")),
  MD004 = list(id="MD-004", label="Standard Markdown",
    outcome="GREEN",
    check="Markdown checked for participant identifiers, sensitive phenotypes, and large embedded tables. None detected.",
    file_types=c("markdown")),

  # ── ACRO/SACRO integration ─────────────────────────────────────────────
  ACR001 = list(id="ACR-001", label="ACRO SDC Check Failed",
    outcome="RED",
    check=paste0(
      "ACRO flagged this output as failing one or more statistical disclosure ",
      "control tests (threshold, p-ratio, nk-rule, dominance). The ACRO session ",
      "recorded specific cells that need suppression or remediation. Review the ",
      "cell-level evidence and the researcher's exception justification."),
    file_types=c("acro_results")),
  ACR002 = list(id="ACR-002", label="ACRO Output Requires Manual Review",
    outcome="AMBER",
    check=paste0(
      "ACRO assigned this output a 'review' status. This typically applies to ",
      "custom outputs (plots, images, non-tabular artefacts) that ACRO cannot ",
      "automatically assess. The researcher has flagged it for human judgement."),
    file_types=c("acro_results")),
  ACR003 = list(id="ACR-003", label="ACRO SDC Checks Passed",
    outcome="GREEN",
    check=paste0(
      "ACRO confirmed this output passed all configured SDC tests (threshold, ",
      "p-ratio, nk-rule). Positive signal from production-time disclosure checking. ",
      "The output may still be flagged by AIRAlock's own egress-time rules."),
    file_types=c("acro_results")),
  ACR004 = list(id="ACR-004", label="ACRO Configuration Discrepancy",
    outcome="AMBER",
    check=paste0(
      "The ACRO session was configured with different SDC thresholds than ",
      "AIRAlock's current configuration (e.g. safe_threshold vs count_threshold). ",
      "The two tools applied different risk appetites at analysis vs egress time."),
    file_types=c("acro_results")),
  ACR005 = list(id="ACR-005", label="ACRO Output File Not in Batch",
    outcome="AMBER",
    check=paste0(
      "The ACRO session references an output file that is not present in the ",
      "current AIRAlock batch. The file may have been omitted, renamed, or the ",
      "researcher chose not to submit it."),
    file_types=c("acro_results")),
  ACR006 = list(id="ACR-006", label="ACRO Checksum Mismatch",
    outcome="AMBER",
    check=paste0(
      "The ACRO session recorded that the checksum for this output file is ",
      "invalid. The submitted file may have been modified after the ACRO session ",
      "was finalised. ACRO's SDC findings reflect the file at analysis time."),
    file_types=c("acro_results")),
  ACR007 = list(id="ACR-007", label="ACRO Session Metadata",
    outcome="GREEN",
    check=paste0(
      "This file is an ACRO results.json session file containing SDC check ",
      "metadata for research outputs produced using the ACRO/SACRO framework. ",
      "Individual output findings are attached to their corresponding files."),
    file_types=c("acro_results"))
)